Add auto_update feature for neovim
skanehira/preview-markdown.vim pull request #23
Opened 2021-09-18 15:40 UTC by AkiraHasegawa1997

Hi,
I'm really sorry to send the same pull request twice.
Since I forgot to make a branch before sending the pull request, I tried to fix it but accidentally closed the previous pull request.

This commits allows to use auto_update feature for Neovim users.

- To save a job id that is made by `termopen`, I made a new variable `s:preview_job_id`.

- To close the buffer of a terminated terminal, I added the following lines:
```
  if has('nvim')
    autocmd TermClose * exe "bd! " . expand('<abuf>')
  endif
```

2021-09-18 15:52 UTC, AkiraHasegawa1997 commented
When I resend the pull request, a critical bug had been introduced, so I fixed it by force push.

2021-09-19 00:09 UTC, AkiraHasegawa1997 commented
Sorry, I did a force-push again. 
I found a bug that when we select `glow` instead of `mdr`, it cannot work correctly due to the autocmd modification. 
So I changed that to do `execute bd` explicitly instead of autocmd.

2021-10-12 13:33 UTC, skanehira requested changes
Thank you :)
I left a comment

2021-10-12 13:33 UTC, skanehira commented on autoload/preview_markdown.vim
> +          execute "bd! " . s:preview_buf_nr
I think we should use `bw! ` to wipe out existed buffer

2021-10-19 03:22 UTC, AkiraHasegawa1997 commented
Thank you for the very helpful comment. I fixed it to use `bw!` instead of `bd!`.

2021-10-19 12:54 UTC, skanehira commented
@AkiraHasegawa1997 Thank you
At last one, could you resolve conflicting?
I'll merge this PR when conflict be resolved

2021-10-20 04:53 UTC, merged

2021-10-20 04:54 UTC, skanehira commented
@AkiraHasegawa1997 thank you :)